### PR TITLE
Make sure download stats work on Hugging Face, improve metadata

### PR DESCRIPTION
**Pull request by NielsRogge**
Hi @wangbinDL,

Thanks for this nice work, great to see the models being released on the hub! Your paper was featured on the daily papers: https://huggingface.co/papers/2410.12628. Would be great to link the models to the paper.

To make download stats work, I wrote a PR similar to https://github.com/THU-MIG/yolov10/pull/168 which I did for the YOLOv10 repository.

It leverages the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) developed by the 🤗 team to make sure a custom PyTorch model like yours:
- automatically inherits `from_pretrained` and `push_to_hub` methods
- have better metadata
- make sure download stats work.

Usage is as follows:

```python
from doclayout_yolo import YOLOv10
from huggingface_hub import hf_hub_download

# Load a pre-trained model
filepath = hf_hub_download(repo_id="juliozhao/DocLayout-YOLO-D4LA-from_scratch", filename="doclayout_yolo_d4la_imgsz1600_from_scratch.pt")
model = YOLOv10(filepath)

# One can optionally push this to the hub
model.push_to_hub("juliozhao/DocLayout-YOLO-D4LA-from_scratch")

# Can now be reloaded as follows (and will increment download count)
model = YOLOv10.from_pretrained("juliozhao/DocLayout-YOLO-D4LA-from_scratch")
```

Besides that, some more suggestions to improve the HF release:

- one could create a Gradio demo on 🤗 Spaces to showcase what the model can do.
- one can link the datasets to the models (by adding them to the model cards)
- one can link the models/datasets to the paper page (by including this link: https://huggingface.co/papers/2410.12628 in the model/dataset cards)
- the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) currently doesn't work for your datasets. See here on how to enable them: https://huggingface.co/docs/datasets/image_dataset#object-detection

Let me know whether you need any help!

Kind regards,

Niels from HF

### CODE REVIEW

**Comment by JulioZhao97** [comment]
Thank you very much for your suggestions! If there are updates I will let you know immediately.

**Comment by wangbinDL** [comment]
Hi @NielsRogge 

Thanks for your valuable suggestions. We've now:

- Used PyTorchModelHubMixin for our model, enabling from_pretrained and push_to_hub.  
- Ensured download stats are working.  
- Created a Gradio demo: https://huggingface.co/spaces/opendatalab/DocLayout-YOLO  
- Linked our datasets to the models and paper: https://huggingface.co/papers/2410.12628  

Your assistance is greatly appreciated!

Best,
Bin

**Comment by NielsRogge** [comment]
Thanks, looking great!

Note that for download stats to work, you will need to run the code snippet above for each of the model repos (basically overwriting them). As the class now inherits from `PyTorchModelHubMixin`, a config.json along with `safetensors` weights will be pushed.

**Comment by JulioZhao97** [comment]
> Thanks, looking great!
> 
> Note that for download stats to work, you will need to run the code snippet above for each of the model repos (basically overwriting them). As the class now inherits from `PyTorchModelHubMixin`, a config.json along with `safetensors` weights will be pushed.

Noted, thanks for your contribution again!

**Comment by NielsRogge** [comment]
Hi @JulioZhao97 are you planning to run the script above?

Cause I see downloads aren't working yet

**Comment by JulioZhao97** [comment]
@NielsRogge Hello! I tried ```model.push_to_hub``` but no model weights found in the repository, could you please tell me where is wrong?
image

Follow is the target repository:
image

**Comment by agombert** [comment]
Hey @JulioZhao97 how did you solve the pb to push to the hub ? Do you need to download the repo to do so as in Niels example ?

**Comment by agombert** [comment]
@NielsRogge thanks for the quick answer

```python
model = YOLOv10.from_pretrained("juliozhao/DocLayout-YOLO-D4LA-from_scratch")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[91], [line 1](vscode-notebook-cell:?execution_count=91&line=1)
----> [1](vscode-notebook-cell:?execution_count=91&line=1) model = YOLOv10.from_pretrained("juliozhao/DocLayout-YOLO-D4LA-from_scratch")

AttributeError: type object 'YOLOv10' has no attribute 'from_pretrained'
```

It happens when I install `doclayout-yolo = "^0.0.2`.

**Pull request merged**
